export const IPC_CHANNELS = {
  library: {
    scan: 'library:scan',
    getTracks: 'library:get-tracks',
    getTrack: 'library:get-track',
    toggleFavorite: 'library:toggle-favorite',
    getCovers: 'library:get-covers',
    getDownloads: 'library:get-downloads',
    fileAdded: 'library:file-added',
    fileRemoved: 'library:file-removed',
    scanProgress: 'library:scan-progress',
    batchAdded: 'library:batch-added',
  },
  player: {
    play: 'player:play',
    pause: 'player:pause',
    resume: 'player:resume',
    togglePlay: 'player:toggle-play',
    next: 'player:next',
    prev: 'player:prev',
    trackEnded: 'player:track-ended',
    recordPlay: 'player:record-play',
    syncProgress: 'player:sync-progress',
    seek: 'player:seek',
    setVolume: 'player:set-volume',
    toggleShuffle: 'player:toggle-shuffle',
    toggleRepeat: 'player:toggle-repeat',
    playbackState: 'player:playback-state',
    timeUpdate: 'player:time-update',
    load: 'player:load',
    seekTo: 'player:seek-to',
  },
  queue: {
    add: 'queue:add',
    addNext: 'queue:add-next',
    set: 'queue:set',
    remove: 'queue:remove',
    reorder: 'queue:reorder',
    clear: 'queue:clear',
    get: 'queue:get',
    updated: 'queue:updated',
  },
  playlist: {
    list: 'playlist:list',
    create: 'playlist:create',
    delete: 'playlist:delete',
    rename: 'playlist:rename',
    getTracks: 'playlist:get-tracks',
    addTracks: 'playlist:add-tracks',
    removeTrack: 'playlist:remove-track',
    reorder: 'playlist:reorder',
  },
  youtube: {
    search: 'youtube:search',
    download: 'youtube:download',
    cancelDownload: 'youtube:cancel-download',
    getHistory: 'youtube:get-history',
    clearHistory: 'youtube:clear-history',
    downloadProgress: 'youtube:download-progress',
    downloadDone: 'youtube:download-done',
    downloadError: 'youtube:download-error',
    downloadStarted: 'youtube:download-started',
    downloadCancelled: 'youtube:download-cancelled',
    historyCleared: 'youtube:history-cleared',
  },
  settings: {
    get: 'settings:get',
    set: 'settings:set',
    getAll: 'settings:get-all',
    getFolders: 'settings:get-folders',
    addFolder: 'settings:add-folder',
    removeFolder: 'settings:remove-folder',
    openFolderDialog: 'settings:open-folder-dialog',
  },
  eq: {
    setBands: 'eq:set-bands',
    setPreset: 'eq:set-preset',
    enable: 'eq:enable',
    getEnabled: 'eq:get-enabled',
    bandsChanged: 'eq:bands-changed',
  },
  lastfm: {
    auth: 'lastfm:auth',
    isAuthd: 'lastfm:is-authd',
    disconnect: 'lastfm:disconnect',
    nowPlaying: 'lastfm:now-playing',
    scrobble: 'lastfm:scrobble',
  },
  system: {
    checkFfmpeg: 'system:check-ffmpeg',
    checkYtDlp: 'system:check-yt-dlp',
    log: 'system:log',
  },
} as const
